AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  apigw-redirect

  Sample SAM Template for apigw-redirect
Globals:
  Function:
    Timeout: 3

Resources:
  RedirectAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: REGIONAL
      # DefinitionBody taken from https://stackoverflow.com/a/54775915/5273367
      DefinitionBody:
        openapi: "3.0.0"
        paths:
          "/":
            get:
              responses:
                "302":
                  description: "302 response"
                  headers:
                    Location:
                      schema:
                        type: "string"
                  content: {}
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: "302"
                    responseParameters:
                      method.response.header.Location: "'https://www.google.com/'"
                requestTemplates:
                  application/json: "{\"statusCode\": 200}"
                passthroughBehavior: "when_no_match"
                type: "mock"


Outputs:
  RedirectAPI:
    Value: !Sub "https://${RedirectAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

